language: node_js
node_js:
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/protractor/bin/install_selenium_standalone
  - java -jar selenium/selenium-server-standalone-2.35.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
  - sleep 3
  - npm install -gq bower codeclimate-test-reporter
  - bower install --dev --config.interactive=0
  - gulp --version
  - bower --version

script:
  - gulp validate:fail
  - gulp dist:unsafe
  - sleep 10
  - gulp unit:travis
  - gulp e2e

after_script:
  - cat coverage/*/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: 90c20f7102c1594756c4ea3462c0603bea217cf25c16d57accea4a03348c2465
