language: node_js
node_js:
  - '0.10'
before_install: npm install -g protractor@1.0.0 mocha@1.18.2 bower codeclimate-test-reporter
install:
  - npm install
  - bower install --dev --config.interactive=0
  - webdriver-manager update --standalone
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - webdriver-manager start &
script:
  - gulp validate:fail
  - gulp dist:unsafe
  - sleep 10
  - gulp unit:travis
  - gulp
  - protractor protractor.conf.js

after_script:
  - cat coverage/*/lcov.info | codeclimate

addons:
  code_climate:
    repo_token: 90c20f7102c1594756c4ea3462c0603bea217cf25c16d57accea4a03348c2465