language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -gq bower
  - bower install --dev --config.interactive=0
  - gulp --version
  - bower --version

script:
  - gulp validate:fail
  - gulp dist:unsafe
  - sleep 10
  - gulp unit
